Improving error handling on docconv

diff --git a/utils/docconv b/utils/docconv
--- a/utils/docconv
+++ b/utils/docconv
@@ -17,4 +17,8 @@ while :; do
     esac
 done
 
+[ -n "$FILE" ] || die "Please specify a file to convert"
+[ -e "$FILE" ] || die "File '$1' not found"
+[ -f "$FILE" ] || die "'$1' is not a file"
+
 pandoc "$FILE" --pdf-engine=pdflatex -o "$BASE"."$FOUT"
